// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Calculator library")]
[assembly: AssemblyDescriptionAttribute("Sample project for FAKE - F# MAKE")]
[assembly: GuidAttribute("EE5621DB-B86B-44eb-987F-9C94BCC98441")]
[assembly: AssemblyProductAttribute("Calculator")]
[assembly: AssemblyVersionAttribute("0.2")]
[assembly: AssemblyFileVersionAttribute("0.2")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.2";
    }
}
