// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Calculator Command line tool")]
[assembly: AssemblyDescriptionAttribute("Sample project for FAKE - F# MAKE")]
[assembly: GuidAttribute("A539B42C-CB9F-4a23-8E57-AF4E7CEE5BAA")]
[assembly: AssemblyProductAttribute("Calculator")]
[assembly: AssemblyVersionAttribute("0.2")]
[assembly: AssemblyFileVersionAttribute("0.2")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.2";
    }
}
